/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#455f00',
        'tertiary-container': '#c1ff2a',
        'on-secondary-fixed': '#00394e',
        'surface-container-low': '#001620',
        'error-dim': '#d7383b',
        'surface-variant': '#00293a',
        'on-surface-variant': '#85b1cb',
        'outline-variant': '#1d4d63',
        'on-primary-fixed-variant': '#004a5c',
        'surface': '#001019',
        'on-error-container': '#ffa8a3',
        'tertiary-fixed-dim': '#b4f012',
        'surface-bright': '#003043',
        'surface-tint': '#69daff',
        'on-background': '#c9eaff',
        'primary-fixed': '#00cffc',
        'primary-container': '#00cffc',
        'secondary-dim': '#00b2ec',
        'error': '#ff716c',
        'primary': '#69daff',
        'secondary-container': '#006688',
        'inverse-surface': '#f5faff',
        'surface-container-lowest': '#000000',
        'tertiary-fixed': '#c1ff2a',
        'on-primary': '#004a5d',
        'surface-container': '#001c29',
        'inverse-primary': '#006880',
        'on-tertiary-fixed': '#364b00',
        'primary-dim': '#00c0ea',
        'on-secondary': '#00374c',
        'on-primary-fixed': '#002a35',
        'background': '#001019',
        'on-surface': '#c9eaff',
        'on-secondary-container': '#f1f9ff',
        'secondary-fixed': '#98daff',
        'error-container': '#9f0519',
        'primary-fixed-dim': '#00c0ea',
        'on-primary-container': '#004050',
        'on-tertiary': '#4c6800',
        'secondary': '#17c0fd',
        'inverse-on-surface': '#2d5a71',
        'tertiary-dim': '#b4f012',
        'secondary-fixed-dim': '#6ecfff',
        'on-error': '#490006',
        'on-tertiary-fixed-variant': '#4d6a00',
        'on-secondary-fixed-variant': '#005775',
        'surface-container-high': '#002331',
        'surface-container-highest': '#00293a',
        'surface-dim': '#001019',
        'tertiary': '#f2ffd0',
        'outline': '#4f7b93',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
